services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    hostname: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpassword}
      POSTGRES_DB: ${POSTGRES_DB:-pgdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    networks:
      - db_network

  mysql:
    image: mysql:9.0
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysqlpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mysqldb}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-initdb.sql:/docker-entrypoint-initdb.d/mysqlinit.sql
    networks:
      - db_network

  mongodb:
    image: mongo:jammy
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-myuser}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mypassword}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-mydb}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb-initdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - db_network

volumes:
  postgres_data:
  mysql_data:
  mongo_data:

networks:
  db_network:

