# name: Notify
# on:
#   push:
#   release:
#     types: [published]

# jobs:
#   notify:
#     name: Notify via Telegram
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send message to Telegram
#         uses: Lukasss93/telegram-action@v2
#         env:
#           TELEGRAM_TOKEN: ${{ secrets.telegram_token }}
#           TELEGRAM_CHAT: ${{ secrets.telegram_chat }}

name: Send Telegram Message

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT }}
          message: "New commit pushed to repository"