name: Bump version
on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.2.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}