
name: semantic version

on:

  workflow_dispatch:

jobs:

  versioning:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          