name: semantic version
on:
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.12.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Send telegram message that a new release has been released
        uses: appleboy/telegram-action@v1.0.0
        if: ${{ steps.release.outputs.released }} == 'true'
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🎉 **New Version Released!** 🚀

            📦 **Version**: ${{ steps.release.outputs.version }}
  
            🔗 [Check out the release notes!](https://github.com/mehranasghari/db-backup/releases)
  