
name: semantic version

on:

  workflow_dispatch:

jobs:

  versioning:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: send telegram message that a new release has been released
        uses: appleboy/telegram-action@master
        if: steps.release.outputs.released == 'true'
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Version ${{ steps.release.outputs.version }} has just been released