name: semver

on:
  - workflow_dispatch

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: version the package
      uses: paulhatch/semantic-version@v5.4.0
      with:
        bump_each_commit: true
        bump_each_commit_patch_pattern: "(PATCH)"
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
